# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '03:00'
      timezone: 'Europe/Amsterdam'
    open-pull-requests-limit: 10

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    patterns:
      - "*"
    multi-ecosystem-group: 'all-dependencies'

  - package-ecosystem: 'npm'
    directory: '/'
    patterns:
      - "*"
    multi-ecosystem-group: 'all-dependencies'

  - package-ecosystem: 'docker'
    directory: '/'
    patterns:
      - "*"
    multi-ecosystem-group: 'all-dependencies'
